// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerbleChat.Backend.Database;

#nullable disable

namespace SerbleChat.Backend.Migrations
{
    [DbContext(typeof(ChatDatabaseContext))]
    partial class ChatDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Channel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("VoiceCapable")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Channels");

                    b.HasAnnotation("Relational:JsonPropertyName", "channel");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ChannelPermissionOverride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ChannelPermissionOverrides");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ChannelRead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastReadMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId", "ChannelId")
                        .IsUnique();

                    b.ToTable("ChannelReads");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ChatUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Blurb")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NotificationsWhileOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ClientOptionsData", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("ClientOptions");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.DmChannel", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("User1Id")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("User2Id")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ChannelId");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("DmChannels");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Friendship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Pending")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("User1Id")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("User2Id")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GroupChat", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ChannelId");

                    b.HasIndex("OwnerId");

                    b.ToTable("GroupChats");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GroupChatMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GroupChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupChatId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupChatMembers");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Guild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Guilds");

                    b.HasAnnotation("Relational:JsonPropertyName", "guild");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Until")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique();

                    b.ToTable("GuildBans");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildChannel", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("ChannelId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildChannels");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildInvite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildInvites");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.MessageMention", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId");

                    b.ToTable("MessageMentions");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<bool>("DisplaySeparately")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Mentionable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlockedUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("UserId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("UserBlocks");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserChannelNotificationPreferences", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId", "ChannelId")
                        .IsUnique();

                    b.ToTable("UserChannelNotificationPreferences");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserGuildNotificationPreferences", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique();

                    b.ToTable("UserGuildNotificationPreferences");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserRoleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoleAssignments");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserWebNotificationHook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserWebNotificationHooks");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Channel", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Guild", "GuildNavigation")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GuildNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ChannelPermissionOverride", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "ChannelNavigation")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.Role", "RoleNavigation")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SerbleChat.Backend.Schemas.GuildPermissions", "Permissions", b1 =>
                        {
                            b1.Property<long>("ChannelPermissionOverrideId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Administrator")
                                .HasColumnType("int");

                            b1.Property<int>("BanMembers")
                                .HasColumnType("int");

                            b1.Property<int>("CreateInvites")
                                .HasColumnType("int");

                            b1.Property<int>("DeafenMembers")
                                .HasColumnType("int");

                            b1.Property<int>("JoinVoice")
                                .HasColumnType("int");

                            b1.Property<int>("KickMembers")
                                .HasColumnType("int");

                            b1.Property<int>("ManageChannels")
                                .HasColumnType("int");

                            b1.Property<int>("ManageGuild")
                                .HasColumnType("int");

                            b1.Property<int>("ManageMessages")
                                .HasColumnType("int");

                            b1.Property<int>("ManageRoles")
                                .HasColumnType("int");

                            b1.Property<int>("MoveMembers")
                                .HasColumnType("int");

                            b1.Property<int>("MuteMembers")
                                .HasColumnType("int");

                            b1.Property<int>("SendMessages")
                                .HasColumnType("int");

                            b1.Property<int>("Speak")
                                .HasColumnType("int");

                            b1.Property<int>("VideoStream")
                                .HasColumnType("int");

                            b1.Property<int>("ViewChannel")
                                .HasColumnType("int");

                            b1.HasKey("ChannelPermissionOverrideId");

                            b1.ToTable("ChannelPermissionOverrides");

                            b1.WithOwner()
                                .HasForeignKey("ChannelPermissionOverrideId");
                        });

                    b.Navigation("ChannelNavigation");

                    b.Navigation("Permissions")
                        .IsRequired();

                    b.Navigation("RoleNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ChannelRead", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "ChannelNavigation")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ChatUser", b =>
                {
                    b.OwnsOne("SerbleChat.Backend.Schemas.NotificationPreferences", "DefaultDmNotificationPreferences", b1 =>
                        {
                            b1.Property<string>("ChatUserId")
                                .HasColumnType("varchar(64)");

                            b1.Property<int>("Notifications")
                                .HasColumnType("int");

                            b1.Property<int>("Unreads")
                                .HasColumnType("int");

                            b1.HasKey("ChatUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("ChatUserId");
                        });

                    b.OwnsOne("SerbleChat.Backend.Schemas.NotificationPreferences", "DefaultGroupNotificationPreferences", b1 =>
                        {
                            b1.Property<string>("ChatUserId")
                                .HasColumnType("varchar(64)");

                            b1.Property<int>("Notifications")
                                .HasColumnType("int");

                            b1.Property<int>("Unreads")
                                .HasColumnType("int");

                            b1.HasKey("ChatUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("ChatUserId");
                        });

                    b.OwnsOne("SerbleChat.Backend.Schemas.NotificationPreferences", "DefaultGuildNotificationPreferences", b1 =>
                        {
                            b1.Property<string>("ChatUserId")
                                .HasColumnType("varchar(64)");

                            b1.Property<int>("Notifications")
                                .HasColumnType("int");

                            b1.Property<int>("Unreads")
                                .HasColumnType("int");

                            b1.HasKey("ChatUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("ChatUserId");
                        });

                    b.Navigation("DefaultDmNotificationPreferences")
                        .IsRequired();

                    b.Navigation("DefaultGroupNotificationPreferences")
                        .IsRequired();

                    b.Navigation("DefaultGuildNotificationPreferences")
                        .IsRequired();
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.ClientOptionsData", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.DmChannel", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "ChannelNavigation")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "User1Navigation")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "User2Navigation")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelNavigation");

                    b.Navigation("User1Navigation");

                    b.Navigation("User2Navigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Friendship", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "User1Navigation")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "User2Navigation")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1Navigation");

                    b.Navigation("User2Navigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GroupChat", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "ChannelNavigation")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "OwnerNavigation")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelNavigation");

                    b.Navigation("OwnerNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GroupChatMember", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.GroupChat", "GroupChatNavigation")
                        .WithMany()
                        .HasForeignKey("GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChatNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Guild", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "OwnerNavigation")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SerbleChat.Backend.Schemas.GuildPermissions", "DefaultPermissions", b1 =>
                        {
                            b1.Property<long>("GuildId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Administrator")
                                .HasColumnType("int");

                            b1.Property<int>("BanMembers")
                                .HasColumnType("int");

                            b1.Property<int>("CreateInvites")
                                .HasColumnType("int");

                            b1.Property<int>("DeafenMembers")
                                .HasColumnType("int");

                            b1.Property<int>("JoinVoice")
                                .HasColumnType("int");

                            b1.Property<int>("KickMembers")
                                .HasColumnType("int");

                            b1.Property<int>("ManageChannels")
                                .HasColumnType("int");

                            b1.Property<int>("ManageGuild")
                                .HasColumnType("int");

                            b1.Property<int>("ManageMessages")
                                .HasColumnType("int");

                            b1.Property<int>("ManageRoles")
                                .HasColumnType("int");

                            b1.Property<int>("MoveMembers")
                                .HasColumnType("int");

                            b1.Property<int>("MuteMembers")
                                .HasColumnType("int");

                            b1.Property<int>("SendMessages")
                                .HasColumnType("int");

                            b1.Property<int>("Speak")
                                .HasColumnType("int");

                            b1.Property<int>("VideoStream")
                                .HasColumnType("int");

                            b1.Property<int>("ViewChannel")
                                .HasColumnType("int");

                            b1.HasKey("GuildId");

                            b1.ToTable("Guilds");

                            b1.WithOwner()
                                .HasForeignKey("GuildId");
                        });

                    b.Navigation("DefaultPermissions")
                        .IsRequired();

                    b.Navigation("OwnerNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildBan", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Guild", "GuildNavigation")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildChannel", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "ChannelNavigation")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.Guild", "GuildNavigation")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelNavigation");

                    b.Navigation("GuildNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildInvite", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Guild", "GuildNavigation")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.GuildMember", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Guild", "GuildNavigation")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Message", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "AuthorNavigation")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "ChannelNavigation")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorNavigation");

                    b.Navigation("ChannelNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.MessageMention", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Message", "MessageNavigation")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.Role", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Guild", "GuildNavigation")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SerbleChat.Backend.Schemas.GuildPermissions", "Permissions", b1 =>
                        {
                            b1.Property<long>("RoleId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Administrator")
                                .HasColumnType("int");

                            b1.Property<int>("BanMembers")
                                .HasColumnType("int");

                            b1.Property<int>("CreateInvites")
                                .HasColumnType("int");

                            b1.Property<int>("DeafenMembers")
                                .HasColumnType("int");

                            b1.Property<int>("JoinVoice")
                                .HasColumnType("int");

                            b1.Property<int>("KickMembers")
                                .HasColumnType("int");

                            b1.Property<int>("ManageChannels")
                                .HasColumnType("int");

                            b1.Property<int>("ManageGuild")
                                .HasColumnType("int");

                            b1.Property<int>("ManageMessages")
                                .HasColumnType("int");

                            b1.Property<int>("ManageRoles")
                                .HasColumnType("int");

                            b1.Property<int>("MoveMembers")
                                .HasColumnType("int");

                            b1.Property<int>("MuteMembers")
                                .HasColumnType("int");

                            b1.Property<int>("SendMessages")
                                .HasColumnType("int");

                            b1.Property<int>("Speak")
                                .HasColumnType("int");

                            b1.Property<int>("VideoStream")
                                .HasColumnType("int");

                            b1.Property<int>("ViewChannel")
                                .HasColumnType("int");

                            b1.HasKey("RoleId");

                            b1.ToTable("Roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("GuildNavigation");

                    b.Navigation("Permissions")
                        .IsRequired();
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserBlock", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "BlockedUserNavigation")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUserNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserChannelNotificationPreferences", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "ChannelNavigation")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SerbleChat.Backend.Schemas.NotificationPreferences", "Preferences", b1 =>
                        {
                            b1.Property<long>("UserChannelNotificationPreferencesId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Notifications")
                                .HasColumnType("int");

                            b1.Property<int>("Unreads")
                                .HasColumnType("int");

                            b1.HasKey("UserChannelNotificationPreferencesId");

                            b1.ToTable("UserChannelNotificationPreferences");

                            b1.WithOwner()
                                .HasForeignKey("UserChannelNotificationPreferencesId");
                        });

                    b.Navigation("ChannelNavigation");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserGuildNotificationPreferences", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Channel", "GuildNavigation")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SerbleChat.Backend.Schemas.NotificationPreferences", "Preferences", b1 =>
                        {
                            b1.Property<long>("UserGuildNotificationPreferencesId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Notifications")
                                .HasColumnType("int");

                            b1.Property<int>("Unreads")
                                .HasColumnType("int");

                            b1.HasKey("UserGuildNotificationPreferencesId");

                            b1.ToTable("UserGuildNotificationPreferences");

                            b1.WithOwner()
                                .HasForeignKey("UserGuildNotificationPreferencesId");
                        });

                    b.Navigation("GuildNavigation");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserRoleAssignment", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.Role", "RoleNavigation")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("SerbleChat.Backend.Database.Structs.UserWebNotificationHook", b =>
                {
                    b.HasOne("SerbleChat.Backend.Database.Structs.ChatUser", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
